name: formfun_flutter_test
description: "Form&Fun Flutter Test"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/animations/

  fonts:
    - family: AktivGrotesk
      fonts:
        - asset: assets/fonts/AktivGrotesk_Hair.ttf
          weight: 100
        - asset: assets/fonts/AktivGrotesk_Th.ttf
          weight: 200
        - asset: assets/fonts/AktivGrotesk_Lt.ttf
          weight: 300
        - asset: assets/fonts/AktivGrotesk_Rg.ttf
          weight: 400
        - asset: assets/fonts/AktivGrotesk_Md.ttf
          weight: 500
        - asset: assets/fonts/AktivGrotesk_SBd.ttf
          weight: 600
        - asset: assets/fonts/AktivGrotesk_Bd.ttf
          weight: 700
        - asset: assets/fonts/AktivGrotesk_XBd.ttf
          weight: 800
        - asset: assets/fonts/AktivGrotesk_Blk.ttf
          weight: 900
