name: widgetbook_workspace
description: "Form&Fun Flutter Test - Widgetbook Workspace"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.20.2
  widgetbook_annotation: ^3.9.0
  formfun_flutter_test:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.20.1
  build_runner: ^2.10.4
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "../assets/images/ff_logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "../assets/images/ff_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/animations/

  fonts:
    - family: AktivGrotesk
      fonts:
        - asset: assets/fonts/AktivGrotesk_Hair.ttf
          weight: 100
        - asset: assets/fonts/AktivGrotesk_Th.ttf
          weight: 200
        - asset: assets/fonts/AktivGrotesk_Lt.ttf
          weight: 300
        - asset: assets/fonts/AktivGrotesk_Rg.ttf
          weight: 400
        - asset: assets/fonts/AktivGrotesk_Md.ttf
          weight: 500
        - asset: assets/fonts/AktivGrotesk_SBd.ttf
          weight: 600
        - asset: assets/fonts/AktivGrotesk_Bd.ttf
          weight: 700
        - asset: assets/fonts/AktivGrotesk_XBd.ttf
          weight: 800
        - asset: assets/fonts/AktivGrotesk_Blk.ttf
          weight: 900
